-- ========================================================
-- HOMEWORK PLATFORMASI UCHUN SUPABASE MA'LUMOTLAR BAZASI
-- Ushbu SQL kodni Supabase boshqaruv panelidagi
-- "SQL Editor" bo'limida ishga tushiring (Run qiling).
-- ========================================================

-- 1. Users jadvaliga qo'shimcha maydonlar qo'shish (agar mavjud bo'lmasa)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS parent_phone TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS group_name TEXT;

-- 2. Assignments (Topshiriqlar) jadvalini yaratish
CREATE TABLE IF NOT EXISTS public.assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  group_name TEXT NOT NULL,
  teacher_name TEXT,
  type TEXT,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'Faol',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) qoidalari
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to assignments" ON public.assignments;
CREATE POLICY "Allow all access to assignments" ON public.assignments
  FOR ALL USING (true) WITH CHECK (true);

-- 3. Submissions (Topshirilgan vazifalar va natijalar) jadvalini yaratish
CREATE TABLE IF NOT EXISTS public.submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT,
  assignment_title TEXT,
  student_login TEXT NOT NULL,
  student_name TEXT,
  score INTEGER DEFAULT 0,
  total_questions INTEGER DEFAULT 0,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS qoidalari
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to submissions" ON public.submissions;
CREATE POLICY "Allow all access to submissions" ON public.submissions
  FOR ALL USING (true) WITH CHECK (true);

-- 4. Barcha jadvallarga anon va authenticated ruxsatlarini berish
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.groups TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.assignments TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.submissions TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
